### ISSUE TITLE
[feature request] rename ancient magic teleport options (and Marim)

### ISSUE THREAD

**Issue by ThimbleFire** [abextm/better-teleport-menu#1]
Thought this might be up your alley. https://github.com/runelite/runelite/issues/13092

Sorry if this is a bit rude to make a request this way, just thought since you've dabbled with the portal nexus before you might be up for doing this.

**Comment by clawzk00** [comment]
Custom names for teleports would be great.

**Comment by abextm** [comment]
Added in 7c6f2a3ce4cd2f66baac50212512cb58d2032b98
