### ISSUE TITLE
Doesn't work when there are too many menu options

### ISSUE THREAD

**Issue by ShaunDreclin** [abextm/better-teleport-menu#10]
Ran into this issue when using the plugin for the globetrotter pendant in the new trailblazer league. None of the options after troll stronghold can be keybound

![Screenshot 1](https://github.com/abextm/better-teleport-menu/assets/5851433/f02d8ddb-02d1-48c1-98be-c1840035bdba)
![Screenshot 2](https://github.com/abextm/better-teleport-menu/assets/5851433/8a91c454-9994-45cf-9e3d-0aa5f57398d6)

**Comment by abextm** [comment]
This happens with fairy's flight too, though less egregiously. 
Fixed in 80d1664fc5ec58dfcec633d1a4a5881e9ec16fe5
