### ISSUE TITLE
Spirit Trees no longer available after installing Better Tele Menu

### ISSUE THREAD

**Issue by GalenCogburn** [abextm/better-teleport-menu#12]
Been playing leagues.  Got the new relic yesterday and it was working fine.  Then, I instlled the "Better Teleport Menu", and the Spirit Tree options that should be available are grayed out (not marked through like the items that are not allowed) and clicking on any of them thow an error that there "Is not a tree planted there".  Not sure the menu caused this, but that is when the issue started and others playing without this add-in do not appear to have this issue.

**Comment by abextm** [comment]
If it says there is no tree planted there and they are greyed out, the server doesn't think there is a tree there and it has nothing to do with the plugin.
