### ISSUE TITLE
[Bug] Blank Maps on Spirit Tree Map caused by Better Teleport Menu

### ISSUE THREAD

**Issue by Nick2bad4u** [abextm/better-teleport-menu#17]
https://github.com/MJHylkema/spirit-tree-map/issues/32#issuecomment-2433477759

Got the same Issue , seems to be a conflict with Better Teleport Menu plugin, Happens to me when I open the teleport menu or using teleports thru the quick teleport menu on Achievement Diary cape. Turning off Better Teleport Menu(wont be fixed if turned on again) or restarting client fixes it.

EDIT: Seems its the Expand scroll menu option in Better teleport Menu that causing the issue. ![image](https://private-user-images.githubusercontent.com/65094845/379465088-2c619d76-bbd1-4080-be8e-8ac2ac8c130a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mjc2NjksIm5iZiI6MTcyOTgyNzM2OSwicGF0aCI6Ii82NTA5NDg0NS8zNzk0NjUwODgtMmM2MTlkNzYtYmJkMS00MDgwLWJlOGUtOGFjMmFjOGMxMzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAzMzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMTA2NTZkOTIwYTUwNzYxNGQ1NmE2ODUzNGVlNDRkMDVjMGMyMDY1YTFmYjEyYzdmYzA1MDQwMjk2MTQ4ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dXio4Ww2agrgrsjBI6tYrAAEKVkKTIQqRzkoyVJzz4U) ![image](https://private-user-images.githubusercontent.com/65094845/379465175-f014ef5f-d406-49ef-afa7-b383c26b3a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mjc2NjksIm5iZiI6MTcyOTgyNzM2OSwicGF0aCI6Ii82NTA5NDg0NS8zNzk0NjUxNzUtZjAxNGVmNWYtZDQwNi00OWVmLWFmYTctYjM4M2MyNmIzYTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAzMzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNTE0YWUyZTZlOTExMmUxMjFkMGVjZWQ3YjVlMGQyMDhmOGY1YjA4OGQyZGIxMWU5ZGFlNzk5NDJmNzhiN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FX1IeRzSZObt-hA-ia1gsoB51ihckJLOqOQ8WFqdGyc) ![image](https://private-user-images.githubusercontent.com/65094845/379465443-a8fb2e9c-7dc1-49b1-8ae5-83be420f848a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mjc2NjksIm5iZiI6MTcyOTgyNzM2OSwicGF0aCI6Ii82NTA5NDg0NS8zNzk0NjU0NDMtYThmYjJlOWMtN2RjMS00OWIxLThhZTUtODNiZTQyMGY4NDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAzMzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MmE3NGVmOTlmNTBkMmQ2YzUyNDc5NTEyZDUyMjg1MGMyZmNkYzc4NzgyMzEzMDE5ODYxYWJkMmY0YmFhMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bgrUvMfvm3_jUVzN7gOyjQyBqQ6kx_9eXo6g5AfcRY0) ![image](https://private-user-images.githubusercontent.com/65094845/379465481-b7d538bc-c7c6-4c62-9703-9383d461efe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4Mjc2NjksIm5iZiI6MTcyOTgyNzM2OSwicGF0aCI6Ii82NTA5NDg0NS8zNzk0NjU0ODEtYjdkNTM4YmMtYzdjNi00YzYyLTk3MDMtOTM4M2Q0NjFlZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDAzMzYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNTk5ZDNkMTc2OTcyMDYxN2IyOGUxOGI2Y2FlMGFkZjQ1NWFjMjU3Mjc2ZWQzZjY4OTMyMmI2NTNiZDJmNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pQwbkZRJQ4VFt3pz9F0emTQZe9t3U7b78QIsIzBtCs4)

**Comment by abextm** [comment]
These two features will never work well together, but it should be less bad now with e5c516fa3f0da867eb58c7536571a0541b909b05
