### ISSUE TITLE
In Leagues, areas with the same name but different teleport lcoations are treated as the same for all

### ISSUE THREAD

**Issue by dog123123** [abextm/better-teleport-menu#18]
With the clue relic for instance, if I configure Lumbridge (Windmill) as W and Lumbridge (Bob's axes) as B, they both will be set as B

**Comment by abextm** [comment]
Should be fixed in 5d80dda8b23bbd17597f2a2b1979fd74d534c73f (v1.5.4 - should be live in a few minutes)
