### ISSUE TITLE
Issue reloading Hotkeys in new Clue Compass teleports menu

### ISSUE THREAD

**Issue by mikeweyandt** [abextm/better-teleport-menu#19]
Seems like all locations that are in the form "LOCATION (SUB-LOCATION)" are all getting set to the same hotkey on reload after only setting a single one.

See the attached picture

![osrs-teleport-menu](https://github.com/user-attachments/assets/e61b5b04-be2f-4643-a8ff-066cf21b1fb6)

**Comment by abextm** [comment]
duplicate #18
