### ISSUE TITLE
Allow for multiple keys per teleport

### ISSUE THREAD

**Issue by vitorebom** [abextm/better-teleport-menu#2]
Instead of having my hotkeys all over the place, I'd like to be able to set multiple keys for a teleport, for example:
Currently the jewelry box has 6 jewelry menus, I'd like to press 1 to 6 to select a particular jewel to use then 1 to 6 for the teleport in that jewel. In this way teleporting to castle wars would be 12, edgeville would be 61 and so on.
If possible, also allow that in the portal nexus for more nesting of teleports to keep the keystrokes within a small range only and not the entire keyboard

**Comment by abextm** [comment]
Added in 6ab7070d05800ac6a6c4317d056aa5b800756750
