### ISSUE TITLE
Clue Compass hotkeys not working

### ISSUE THREAD

**Issue by ForestJ316** [abextm/better-teleport-menu#20]
Some Clue Compass hotkeys are not working. For example Y, P doesn't work, but O does.

![cluecompassimg](https://github.com/user-attachments/assets/bf5e8428-c880-46c8-9766-cc12858e1660)

I don't know if this issue is present with other menus.

**Comment by abextm** [comment]
I think you have a hidden disabled entry for P that is taking precedence

**Comment by abextm** [comment]
fixed in 7c4d3dfa0d1f24cfc4b19933ff93e145d5006669 by not matching disabled entries. I've pushed this as 1.5.5, which should be live in a few minutes.
