### ISSUE TITLE
[League] Menu background randomly not loading

### ISSUE THREAD

**Issue by EwyBoy** [abextm/better-teleport-menu#21]
![menu_bug](https://github.com/user-attachments/assets/c810e4e5-bd49-4922-a125-65e1b970f3df)
Like you can see in the video, the menu background _(the paper scroll thingy holding the teleport locations)_ randomly don't load in. The scrollbar and [x] icon to exit always shows up but the teleport menu itself don't.

Sometimes it loads, sometimes it does not. You kinda have to click the teleport compass several time and just hope it loads.
Could be some kind of race condition. The hotkeys work but you can't click any of the invisible teleport links.

I tell me if you need more info or anything else. I am happy to help resolve this issue!

**Comment by EwyBoy** [comment]
Looks like the same issue: https://github.com/abextm/better-teleport-menu/issues/22
Just in another form.

**Comment by abextm** [comment]
upload your client.log from ~/.runelite/logs/client.log and if you have a higher resolution video that too

**Comment by EwyBoy** [comment]
[client.log](https://github.com/user-attachments/files/17952567/client.log)

https://github.com/user-attachments/assets/e3c950a2-05da-4835-b7c0-257adac45336

**Comment by EwyBoy** [comment]
lol, I read the closing of #22 and tested disabling teleport maps.
Now it works flawlessly

**Comment by abextm** [comment]
Open an issue on <https://github.com/MJHylkema/spirit-tree-map>. It probably just needs a few manual priorities.

**Comment by EwyBoy** [comment]
Done deal: https://github.com/MJHylkema/spirit-tree-map/issues/35
