### ISSUE TITLE
Graphical issues when used alongside teleport maps

### ISSUE THREAD

**Issue by Camreth** [abextm/better-teleport-menu#22]
![2024-11-28 23_04_50-RuneLite - Camreth](https://github.com/user-attachments/assets/f8ae5daa-4d81-4c5d-a462-a170ea42d93c)
![2024-11-28 23_05_58-RuneLite - Camreth](https://github.com/user-attachments/assets/76c3d108-f35c-4229-bec0-da1ddd7e0cf8)

When both better teleport menu and teleport maps are enabled the selection screen becomes blank. The options are still there, just invisible. This issue has only appeared since leagues, but is also happening in the main game.

I have also verified this with two friends and it is also happening in both of their clients.

Edit: I was looking around the teleport maps bug reports and found someone else with this issue, it seems to be caused by "expand scroll menu" in btm, disabling this option caused the map to reappear.

**Comment by EwyBoy** [comment]
Almost same issue as I have, definitely related in some way.
https://github.com/abextm/better-teleport-menu/issues/21

**Comment by abextm** [comment]
this is probably a bug in teleport maps, they probably will never work well together.
