### ISSUE TITLE
Expanded scroll menu and Clue Compass interaction

### ISSUE THREAD

**Issue by caraota-png** [abextm/better-teleport-menu#23]
I'm finding that the expanded scroll menu option turns the clue compass menu transparent, and reverts it back to it's normal, un-expanded size, but also disables scrolling.

**Comment by thanosfromfortnite** [comment]
I've been having this happen when interacting with other menu items while the teleport list is up (swapping tabs, closing world map)

**Comment by abextm** [comment]
Oops I broke it trying to fix teleport maps compat. fixed in c859dacd9ad6b5c5e48a3ca43351c91a6146738f (v1.5.7)
