### ISSUE TITLE
Numpad numbers no longer work for unbound 1-9 teleports when plugin is enabled

### ISSUE THREAD

**Issue by letterbit** [abextm/better-teleport-menu#3]
Title basically! Without the plugin enabled you can press 1 or Numpad1 to spirit tree to Tree Gnome Village. With the plugin enabled, you can only press 1. I've opted not to use the plugin until this potentially gets fixed as I like to use both, which sucks because it's great otherwise! Thank you for your time.

**Comment by abextm** [comment]
Added in 3d1a37df8c44d1f36d1f1bbe9e2e12d905ca2474.
There is now an option to alias numpad keys as their number row variants, which is on by default.
