### ISSUE TITLE
When a customizeable menu opens another menu, same hotkeys select from the first menu

### ISSUE THREAD

**Issue by vitorebom** [abextm/better-teleport-menu#5]
When using the max cape in the inventory and I select "Teleports", the teleports menu shows up, when I select "POH Portals" it brings the cons cape poh portals menu but when I input a teleport key, it sends me to the location on the fist menu if mapped there. This only happens if you have the same mapped key on the different menus, if I pick any other teleport than the one highlithgted it functions normally.
![image](https://user-images.githubusercontent.com/55747379/126233947-34057320-9484-459b-9717-95614e75d9a6.png)
![image](https://user-images.githubusercontent.com/55747379/126234047-e4b7eea5-f7ae-4d7a-9408-add813392390.png)
![image](https://user-images.githubusercontent.com/55747379/126234085-b3f0aa8a-0416-4256-b68f-f7fcf271f20a.png)

**Comment by abextm** [comment]
fixed in d45b30d89a7022a1e7751c377be4e5e23f6a325a
