### ISSUE TITLE
Setting a hotkey on the POH wilderness obelisk changes all of the teleports to that key

### ISSUE THREAD

**Issue by derekmu** [abextm/better-teleport-menu#7]
When I set a hotkey for one of the POH wilderness obelisk teleports, then close and reopen the teleport menu, all of the teleports are now stuck with that hotkey.

![image](https://user-images.githubusercontent.com/6192907/188467994-6e587429-0ba7-4c98-b3a3-039d204d1f53.png)

I'd love if the plugin worked correctly with this teleport menu. If that's not possible, is there a way to reset to the default 1-6 hotkeys without losing all my other keybinds?

**Comment by abextm** [comment]
If you are comfortable with editing your config manually, you could remove any keys that start with `betterteleportmenu.keybind.select-obelisk-destination-`.
I think there will just be a `betterteleportmenu.keybind.select-obelisk-destination-wilderness` key if my guess is correct.

**Comment by abextm** [comment]
fixed in 861463154c660373bdf74ce27e298a91bc5704eb
