### ISSUE TITLE
[Bug] Alternate names settings removes ability to teleport to Canifis (and some other locations)

### ISSUE THREAD

**Issue by Nick2bad4u** [abextm/better-teleport-menu#8]
Turned On
![image](https://user-images.githubusercontent.com/20943337/216797131-302977e2-e68a-445a-b670-6edb5d4a9fb7.png)

Turned Off:
![image](https://user-images.githubusercontent.com/20943337/216797135-f78a85ee-4f2e-4e41-9c23-5140c0951db7.png)

Other disabled locations:
![image](https://user-images.githubusercontent.com/20943337/216797148-1364ac3c-d6fe-4426-8027-6a57285d9b04.png)
![image](https://user-images.githubusercontent.com/20943337/216797150-ebcd9431-af05-43d8-ac35-bea7cb1000b3.png)
![image](https://user-images.githubusercontent.com/20943337/216797151-28106ca0-2ae5-48cf-b485-e49e4b630c01.png)

**Comment by abextm** [comment]
This is likely a quirk in the nexus portal map plugin, though I wouldn't really expect these plugins to be compatible with each other at all.
