### ISSUE TITLE
the keypresses are persisted across multiple uses for multi-character teleports

### ISSUE THREAD

**Issue by featurecat** [abextm/better-teleport-menu#9]
On my Spirit Tree, I have farming guild as "F". Jewelry box has "FA"->farming guild, and "A"->Al Kharid. If I have used my spirit tree to go to the farming guild, then I tab back to my house, go to my jewelry box, and press "A", it takes me to the farming guild, even though it should go to Al Kharid.

**Comment by abextm** [comment]
fixed in 8318ce07e3fa01f94862e83297baa982a0fb8670
